# Generated by Django 5.1.1 on 2024-10-14 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('point_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('hr_join', models.TimeField()),
                ('hr_exit', models.TimeField()),
                ('desc', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=60)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('register_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponto.point')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ponto.user')),
            ],
        ),
    ]
